// resources/src/vue/components/routeC.vue
<template>
    <div class="container">
        <div class="home__vue">
            <h1>Route C</h1>
        </div>
    </div>
</template>

<script>

    export default {

        name: "routeC",

        components: {
        },

        props: {
        },

        data: function () {
            return {
            };
        },

        mounted() {
            this.$emit('setSessionData', this.$route.name, window.location.href)
        }

    };

</script>

// resources/src/react/components/routeC.js
import React, { useEffect } from "react";
import useSetSessionData from '../custom-hooks/useSetSessionData.js';

const RouteC = () => {

    useEffect(() => {
        useSetSessionData('/c.html', window.location.href)
    }, [])

    return (

        <div className="container">
            <div className="home__react">
                <h1>Route C</h1>
            </div>
        </div>

    );

};

export default RouteC;
