// resources/src/react/components/routeB.js
import React, { useEffect } from "react";
import useSetSessionData from '../custom-hooks/useSetSessionData.js';

const RouteB = () => {

    useEffect(() => {
        useSetSessionData('/b.html', window.location.href)
    })

    return (

        <div className="container">
            <div className="home__react">
                <h1>Route B</h1>
            </div>
        </div>

    );

};

export default RouteB;

// resources/src/vue/components/routeB.vue
<template>
    <div class="container">
        <div class="home__vue">
            <h1>Route B</h1>
        </div>
    </div>
</template>

<script>

    export default {

        name: "routeB",

        components: {
        },

        props: {
        },

        data: function () {
            return {
            };
        },

        mounted() {
            this.$emit('setSessionData', this.$route.name, window.location.href)
        }

    };

</script>
